env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - windows
  quotes:
    - error
    - single
    - avoidEscape: true
  jsx-quotes:
    - error
    - prefer-single
  react/prop-types:
    - warn
  semi:
    - error
    - always
  keyword-spacing:
    - error
  block-spacing:
    - error
  no-multi-spaces:
    - warn

  react/jsx-no-duplicate-props:
    - error
  react/jsx-no-target-blank:
    - error
  react/jsx-no-useless-fragment:
    - error
  react/void-dom-elements-no-children:
    - error